spring:
  application:
    name: mziuri
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    generate-ddl: false
    show-sql: false
  jjwt:
    duration: 300000
    secret: ${JJWT_SECRET}